server:
  port: 8080
  servlet:
    context-path: /bootcampSantander

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://ebtyfjcgsclohf:24a082442e93941fb711e54764b5d25239464460f55f551c83297f2c42c7c509@ec2-34-206-8-52.compute-1.amazonaws.com:5432/d3ao7bf3s4jfd9
    username: ebtyfjcgsclohf
    password: 24a082442e93941fb711e54764b5d25239464460f55f551c83297f2c42c7c509
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none



application:
  descripton: Projeto criado na DevWeek do bootcamp DIO - Santander
